package ui.controller

import board.Board
import board.Position
import piece.Piece
import ui.view.BoardView

/**
 * Data to be rendered in the [BoardView].
 * Is generated by the [BoardController] as a response to some action, such as when
 * a piece is selected, deselected, or moved with.
 *
 * @author Dominik Hoftych
 */
sealed class RenderObject {

    /**
     * Nothing has changed so there's nothing new to render.
     */
    object Nothing : RenderObject()

    /**
     * The board state has changed somehow, most likely some move was performed, so the board
     * needs to be fully redrawn.
     */
    data class UpdatedBoard(val board: Board) : RenderObject()

    /**
     * A piece was selected, so the square occupied by the piece as well as all squares to which
     * the piece is allowed to move are colored with green color.
     */
    data class SelectedPiece(val piece: Piece, val allowedMoves: Set<Position>) : RenderObject()
}